---
name: foto
description: A new Flutter project.
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

platforms:
  macos:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  contextual_menu:
    git:
      url: https://github.com/nbonamy/contextual_menu
  cupertino_icons: ^1.0.2
  exif: ^3.1.4
  file: ^6.1.4
  filesize: ^2.0.1
  flutter_treeview: ^1.0.7+1
  image_size_getter: ^2.1.1
  intl: ^0.18.0
  macos_ui:
    git:
      url: https://github.com/nbonamy/macos_ui
  pasteboard: ^0.2.0
  path: ^1.8.2
  photo_view: ^0.14.0
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  window_manager: ^0.3.2
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/folders/
    # - assets/i18n/
